# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Remove node modules
      run: rm -rf node_modules

    - name: Remove .next
      run: rm -rf .next

    - name: Install dependencies
      run: yarn install --immutable --immutable-cache --check-cache

    - name: Build application
      run: yarn build
      
    - run: yarn export
    - run: touch ./out/.nojekyll

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.147.7'
        extended: true

    - name: Build Hugo site
      run: |
          cd blogs
          hugo --minify --environment production --baseURL https://www.sadat.me/blogs/
          mkdir -p ../out/blogs
          cp -r public/* ../out/blogs/
    
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: out # The folder the action should deploy.